I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 485, in script
    e ">Oh… uh… whom ar_E you? I thought you w_Er_E Osamco.<"
IOError: Couldn't find file 'litletheme.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 485, in script
    e ">Oh… uh… whom ar_E you? I thought you w_Er_E Osamco.<"
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\ast.py", line 652, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\exports.py", line 1180, in say
    who(what, *args, **kwargs)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\character.py", line 1016, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\character.py", line 817, in do_display
    **display_args)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\character.py", line 566, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\display\core.py", line 2635, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\display\core.py", line 3304, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\audio\audio.py", line 976, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\audio\audio.py", line 920, in periodic_pass
    c.periodic()
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\audio\audio.py", line 409, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\audio\audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\Sam Collins\Desktop\PROGRAMING AND MODDING\Ren'py\renpy-6.99.14.3-sdk\renpy\loader.py", line 555, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'litletheme.mp3'.

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
Hiveswap Friendsim 
Fri Jun 08 01:04:44 2018
